# Generated by Django 5.1.6 on 2025-02-23 23:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subjectmarks",
            unique_together={("student", "subject")},
        ),
    ]
