# Generated by Django 5.1.6 on 2025-02-24 02:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_reportcard"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reportcard",
            unique_together={("student_rank", "date_of_report_card_generation")},
        ),
    ]
