# Generated by Django 5.1.6 on 2025-02-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_reportcard_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportcard",
            name="date_of_report_card_generation",
            field=models.DateField(auto_now_add=True),
        ),
    ]
