# Generated by Django 5.1.6 on 2025-02-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_reportcard_date_of_report_card_generation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportcard",
            name="date_of_report_card_generation",
            field=models.DateField(auto_created=True),
        ),
    ]
